### ISSUE TITLE
issue in lazy loading angular 2

### ISSUE THREAD

**Issue by karishmagupta0406** [beginor/ng-seed#3]
NavigationError {id: 15, url: "/kpiManagement", error: k}
error: k {__zone_symbol__error: Error: Unexpected token < Evaluating http://localhost:3000/components/kpi-management/kpi-managemen…, …}
id: 15
url: "/kpiManagement"
__proto__:
toString: ƒ ()
constructor: ƒ NavigationError(id,url,error)
__proto__: Object

**Comment by beginor** [comment]
please provide more details of your component, error details.

**Comment by karishmagupta0406** [comment]
**app.routes.ts**
import { Routes, RouterModule} from '@angular/router';
import { HomePageComponent } from './components/home/home-page.component'; 

export const RouteComponents = [HomePageComponent];
let routes : Routes = [{ path: 'homePage', component: HomePageComponent , canActivate: [UserAuthRouteGuardAfterLogout,UserAuthRouteGuard]},
{ path: 'kpiManagement', loadChildren: './components/kpi-management/kpi-management.module#KpiManagementModule'}
]; ]

export const AppRoutes = RouterModule.forRoot(routes,{ useHash: true, enableTracing:true});

--------------------------------------------------------------
**app.component.ts**
export class AppComponent{
consotructor(router : Router){
router.event.subscribe((val) =>{})
}
}


---------------------------------------------------
**kpi-management.module.ts**
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { KpiManagementRoutingModule } from './kpi-management-routing.module';
import { DeleteKpiComponent } from './component/delete-kpi/delete-kpi.component';

@NgModule({
imports: [CommonModule, KpiManagementRoutingModule],
declarations: [DeleteKpiComponent ]
})
export class KpiManagementModule { } 

-------------------------------------------------------
kpi-management-routing.module.ts
[‎9/‎25/‎2018 10:26 AM]  Chopra, Raman:  
--------------------------
import { NgModule } from '@angular/core';
import { Routes, RouterModule} from '@angular/router';
import { DeleteKpiComponent } from './component/delete-kpi/delete-kpi.component';

const childRoutes: Routes = [ {path:'', component : DeleteKpiComponent} ];

@NgModule({
imports: [RouterModule.forChild(childRoutes)],
exports: [RouterModule]
})
export class KpiManagementRoutingModule { } 
 
---------------------------------------
These are my files structure when i am trying to lazy load a module then i am getting below error

Unhandled Promise rejection: Unexpected token <
  Evaluating http://localhost:3000/components/kpi-management/kpi-management.module
  Loading ./components/kpi-management/kpi-management.module ; Zone: angular ; Task: Promise.then ; Value: k {__zone_symbol__error: Error: Unexpected token <
  Evaluating http://localhost:3000/components/kpi-management/kpi-managemen…, …} SyntaxError: Unexpected token <
    at eval (<anonymous>)
    at Re (http://localhost:3000/node_modules/systemjs/dist/system.js:4:25555)
    at http://localhost:3000/node_modules/systemjs/dist/system.js:4:33165
    at j (http://localhost:3000/node_modules/systemjs/dist/system.js:4:7597)
    at O (http://localhost:3000/node_modules/systemjs/dist/system.js:4:7092)
    at k (http://localhost:3000/node_modules/systemjs/dist/system.js:4:6072)
    at http://localhost:3000/node_modules/systemjs/dist/system.js:4:39034
    at e.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.min.js:1:19239)
    at Object.onInvoke (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.min.js:14:5710)
    at e.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.min.js:1:19179)
    at n.run (http://localhost:3000/node_modules/zone.js/dist/zone.min.js:1:14963)
    at http://localhost:3000/node_modules/zone.js/dist/zone.min.js:1:12026
    at e.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.min.js:1:19923)
    at Object.onInvokeTask (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.min.js:14:5525)
    at e.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.min.js:1:19844) 
-------------------------------------------------------

**Comment by beginor** [comment]
please change to use angular cli to build your application， systemjs is obsoleted now.
